name: Docker-gpsmerger

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build gpsmerger
      run: docker build . --file Dockerfile --tag gpsmerger:latest
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: gpsmergertest / gpsmergertest
        auto_tag: true
