name: trackmerger-build

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
 
  build:
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: jerray/publish-docker-action@master
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: trackmerger/trackmerger
            auto_tag: true
